import type {
  InvColumnConfig,
  InvColumnKey,
  QuoteColumnConfig,
  QuoteColumnKey,
} from "../types";

/** 재고 테이블 칼럼 정의 (표시 순서) */
export const INV_COLUMNS: InvColumnConfig[] = [
  { key: "item_no", label: "품번" },
  { key: "item_name", label: "품명" },
  { key: "category", label: "분류" },
  { key: "brand", label: "브랜드" },
  { key: "importer", label: "수입사" },
  { key: "volume_ml", label: "용량" },
  { key: "supply_price", label: "공급가" },
  { key: "discount_price", label: "할인공급가" },
  { key: "wholesale_price", label: "도매가" },
  { key: "retail_price", label: "판매가" },
  { key: "min_price", label: "최저판매가" },
  { key: "vintage", label: "빈티지" },
  { key: "alcohol_content", label: "알콜도수" },
  { key: "country", label: "국가" },
  { key: "barcode", label: "바코드" },
  { key: "stock_excl_available", label: "가용재고제외" },
  { key: "pending_shipment", label: "출고예정" },
  { key: "total_stock", label: "재고수량" },
  { key: "available_stock", label: "가용재고" },
  { key: "bonded_warehouse", label: "보세창고", cdvOnly: true },
  { key: "yongma_logistics", label: "용마로지스", cdvOnly: true },
  { key: "yongma_reserve", label: "용마블락", cdvOnly: true },
  { key: "yongma_marketing", label: "마케팅블락", cdvOnly: true },
  { key: "yongma_sales1", label: "1부블락", cdvOnly: true },
  { key: "yongma_sales2", label: "2부블락", cdvOnly: true },
  { key: "anseong_warehouse", label: "안성창고", dlOnly: true },
  { key: "gig_warehouse", label: "GIG", dlOnly: true },
  { key: "gig_marketing", label: "GIG마케팅", dlOnly: true },
  { key: "gig_sales1", label: "GIG영업1", dlOnly: true },
  { key: "incoming_stock", label: "미착품" },
  { key: "sales_30days", label: "30일출고" },
  { key: "avg_sales_90d", label: "90일평균출고" },
  { key: "avg_sales_365d", label: "365일평균출고" },
];

export const DEFAULT_INV_CDV: InvColumnKey[] = [
  "item_no",
  "item_name",
  "supply_price",
  "min_price",
  "total_stock",
  "bonded_warehouse",
  "sales_30days",
];

export const DEFAULT_INV_DL: InvColumnKey[] = [
  "item_no",
  "item_name",
  "supply_price",
  "min_price",
  "total_stock",
  "anseong_warehouse",
  "sales_30days",
];

/** 견적 테이블 칼럼 정의 */
export const QUOTE_COLUMNS: QuoteColumnConfig[] = [
  { key: "item_code", label: "품목코드" },
  { key: "category", label: "분류" },
  { key: "barcode", label: "바코드" },
  { key: "country", label: "국가" },
  { key: "brand", label: "브랜드" },
  { key: "region", label: "지역" },
  { key: "grape_varieties", label: "포도품종", type: "text" },
  { key: "image_url", label: "이미지" },
  { key: "vintage", label: "빈티지" },
  { key: "product_name", label: "상품명" },
  { key: "english_name", label: "영문명" },
  { key: "korean_name", label: "한글명" },
  { key: "supply_price", label: "공급가", type: "currency" },
  { key: "min_price", label: "최저판매가", type: "currency" },
  { key: "retail_price", label: "판매가", type: "currency" },
  { key: "discount_rate", label: "할인율", editable: true, type: "percent" },
  { key: "discounted_price", label: "할인가", editable: true, type: "computed" },
  { key: "retail_discounted_price", label: "할인판매가", editable: true, type: "computed" },
  { key: "quantity", label: "수량", editable: true, type: "number" },
  { key: "normal_total", label: "정상공급가합계", type: "computed" },
  { key: "discount_total", label: "할인공급가합계", type: "computed" },
  { key: "min_price_total", label: "최저판매가합계", type: "computed" },
  { key: "retail_normal_total", label: "정상판매가합계", type: "computed" },
  { key: "retail_discount_total", label: "할인판매가합계", type: "computed" },
  { key: "tasting_note", label: "테이스팅노트", type: "text" },
  { key: "note", label: "비고", editable: true, type: "text" },
];

export const DEFAULT_QUOTE_VISIBLE: QuoteColumnKey[] = [
  "item_code",
  "product_name",
  "supply_price",
  "discount_rate",
  "discounted_price",
  "quantity",
  "normal_total",
  "discount_total",
  "note",
];
